name: ci

on:
  pull_request:
  push:

jobs:
  ci:
    strategy:
      matrix:
        php-versions: [ '8.2' ]
        composer-versions: ['update --prefer-dist']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup composer versions
        run: composer ${{ matrix.composer-versions }}

      - name: PHPCSFixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --show-progress=none
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

      - name: PHPStan
        run: vendor/bin/phpstan

      - name: Psalm
        run: vendor/bin/psalm

      - name: PHPUnit
        run: vendor/bin/phpunit
        env:
          XDEBUG_MODE: coverage

      - name: CoverageCheck
        run: vendor/bin/coverage-check .build/coverage/clover.xml 100

      - name: PHP Infection
        run: vendor/bin/infection --skip-initial-tests --threads=64 --coverage=.build/coverage
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./.build/coverage/clover.xml
